### ISSUE TITLE
No update for 7 days.

### ISSUE THREAD

**Issue by m3nu** [tomw1808/newscombinator#7]
Something broken in the code or the backend server?

**Comment by tomw1808** [comment]
Unfortunately, yes. Just about to repair it, already ordered new servers.

See http://www.newscombinator.com/

Will update the ticket when done. Hopefully this weekend.

**Comment by m3nu** [comment]
Sorry to hear that. Let me know if you need any help with server deployment. vpsdime.com may be a good fit since they offer lots of RAM. Also cheap. Can't help with the web app though and don't see where the data is scraped from the input sites.

**Comment by tomw1808** [comment]
Hey thanks for the link,

I'm currently hosting all my things (not only the newscombinator) on Hetzner Servers. Imho still best value for money if no PCI/DSS certifications needed (which I definitely don't need atm).

I am also not in need of a lot of RAM, 32 GiB are more than enough. Fast Storage is what I am looking for, which is currently enough for the index with textual data. Images are on S3 anyways...

Also, sometimes murphey strikes: It would all be not a big deal if I had a backup of the database. Three weeks ago my developer machine here broke and I thought I can just swipe the Harddrive (with another few dumps and virtual machines) and re-install from scratch, because the server is creating its own backups anyways, what could possibly go wrong with that idea... :)

I guess tomorrow the Newscombinator is going back online, togehter with BabbleAway.

Thanks for waiting and apologies again for the outage.

**Comment by tomw1808** [comment]
Just some updates:

On the good side:
Migrated the software from the old server to the new one and started back-importing from Solr to MySQL. Except of the Customer data (filters, etc...) all the data is safe and will be re-imported. 

On the downside:
At the current importing speed the batch-process will be finished anywhere from 8h-16h. I know its not really fast and I don't see a quick solution to speed that up due to constraints between the urls and their attributes. 

More updates to come.

**Comment by tomw1808** [comment]
Good news: It is up and running again. 

https://reader.newscombinator.com

Thanks.

**Comment by m3nu** [comment]
Sweet.
